"""Check that the Bedrock v2 prose, machine-readable contract, JSON Schema and
worked examples agree.

Run from the repository root:

    uv run --no-project --with pyyaml --with jsonschema python contract/check.py

Exit 0 when everything agrees; otherwise every disagreement is printed and the
exit code is 1. The reference projector below replays each example's acts and,
after every act, rebuilds every record's state from the acts that still stand
(the latest standing act wins). It records every transition it observes, so the
check also proves that the transition table is consistent with the act rules,
that every listed transition is exercised by at least one example, that no act
changes a record outside its one-step reach (no cascading), and that no act is
ever generated by a state change.
"""

from __future__ import annotations

import copy
import json
import re
import sys
from datetime import datetime, timedelta
from pathlib import Path

import jsonschema
import yaml

ROOT = Path(__file__).resolve().parent
PROSE = ROOT / "bedrock-v2.md"
CONTRACT = ROOT / "bedrock-v2.yaml"
SCHEMA = ROOT / "bedrock-v2.schema.json"
EXAMPLES = ROOT / "examples"
NO_LOOP_EXAMPLE = "contract/examples/10-no-recursive-invalidation.yaml"

# Review 1 removed these state words; none may come back as a state, an
# outcome, or a backticked word in the prose.
REMOVED_STATE_WORDS = [
    "in_force", "open", "addressing", "closed", "tolerated", "evaluating",
    "assuring", "current", "accepted", "declined", "retired",
]
# Review 1 removed two-phase acts.
REMOVED_PHASE_WORDS = ["begun", "completed"]
WITHDRAWN = ("superseded", "revoked")

errors: list[str] = []


def fail(msg: str) -> None:
    errors.append(msg)


# --------------------------------------------------------------------------
# Prose tables
# --------------------------------------------------------------------------


def prose_table(text: str, heading: str) -> list[list[str]]:
    """Rows of the first Markdown table after the given heading line."""
    lines = text.splitlines()
    try:
        start = next(i for i, line in enumerate(lines) if line.strip() == heading)
    except StopIteration:
        fail(f"prose: heading {heading!r} not found")
        return []
    rows: list[list[str]] = []
    in_table = False
    for line in lines[start + 1 :]:
        if line.startswith("#"):
            break
        if line.startswith("|"):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if not in_table:
                in_table = True  # header row
                continue
            if all(set(c) <= set("-: ") for c in cells):
                continue  # separator row
            rows.append(cells)
        elif in_table:
            break
    if not rows:
        fail(f"prose: no table rows under {heading!r}")
    return rows


def words(cell: str) -> list[str]:
    """Backticked words of a cell, in order."""
    return re.findall(r"`([^`]+)`", cell)


def check_prose(text: str, contract: dict) -> None:
    nouns = contract["nouns"]

    rows = prose_table(text, "### The nouns")
    prose_nouns = {r[0].strip("*"): r for r in rows}
    if list(prose_nouns) != list(nouns):
        fail(f"nouns: prose {list(prose_nouns)} != contract {list(nouns)}")
    for name, row in prose_nouns.items():
        spec = nouns.get(name)
        if not spec:
            continue
        if words(row[1]) != [spec["prefix"]]:
            fail(f"noun {name}: prose prefix {words(row[1])} != {spec['prefix']}")
        if words(row[2]) != spec["states"]:
            fail(f"noun {name}: prose states {words(row[2])} != {spec['states']}")
        if words(row[3]) != [spec["made_by"]]:
            fail(f"noun {name}: prose made-by {words(row[3])} != {spec['made_by']}")

    plan = contract["group"]["Plan"]
    m = re.search(r"A Plan's states are ((?:`[a-z_]+`(?:,|\s|and)*)+)", text)
    if not m or words(m.group(1)) != plan["states"]:
        fail(f"Plan: prose must say \"A Plan's states are\" {plan['states']}")

    verbs = contract["verbs"]
    rows = prose_table(text, "### The thirteen verbs")
    prose_verbs = [words(r[1])[0] if words(r[1]) else r[1] for r in rows]
    if prose_verbs != list(verbs):
        fail(f"verbs: prose {prose_verbs} != contract {list(verbs)}")
    for row in rows:
        name = words(row[1])[0] if words(row[1]) else row[1]
        spec = verbs.get(name)
        if not spec:
            continue
        if row[2] != spec["kind"]:
            fail(f"verb {name}: prose kind {row[2]!r} != {spec['kind']!r}")
        if sorted(words(row[3])) != sorted(spec["acts_on"]):
            fail(f"verb {name}: prose acts-on {words(row[3])} != {spec['acts_on']}")
    if len(verbs) != 13:
        fail(f"verbs: contract lists {len(verbs)} verbs, not 13")

    rows = prose_table(text, "### Structural acts")
    prose_structural = [words(r[0])[0] for r in rows if words(r[0])]
    if prose_structural != list(contract["structural_acts"]):
        fail(f"structural acts: prose {prose_structural} != {list(contract['structural_acts'])}")

    rows = prose_table(text, "### Act nodes, verb by verb")
    seen = []
    for row in rows:
        name = words(row[0])[0] if words(row[0]) else row[0]
        seen.append(name)
        spec = verbs.get(name)
        if not spec:
            fail(f"act table: unknown verb {name}")
            continue
        if sorted(words(row[1])) != sorted(spec["inputs"]):
            fail(f"act {name}: prose inputs {words(row[1])} != {spec['inputs']}")
        if sorted(words(row[2])) != sorted(spec["outputs"]):
            fail(f"act {name}: prose outputs {words(row[2])} != {spec['outputs']}")
        if sorted(words(row[3])) != sorted(spec["roles"]):
            fail(f"act {name}: prose roles {words(row[3])} != {spec['roles']}")
    performed = [v for v, s in verbs.items() if s["kind"] == "act"]
    if seen != performed:
        fail(f"act table: prose verbs {seen} != performed verbs {performed}")

    rows = prose_table(text, "### Transitions")
    prose_tr = []
    for r in rows:
        noun, frm, to, by = r[0], words(r[1]), words(r[2]), words(r[3])
        recompute = len(r) > 4 and r[4] == "recomputed"
        prose_tr.append((noun, tuple(frm), to[0] if to else None, tuple(by), recompute))
    yaml_tr = [
        (t["noun"], tuple(t["from"]), t["to"], tuple(t["by"]), bool(t.get("recompute")))
        for t in contract["transitions"]
    ]
    if prose_tr != yaml_tr:
        missing = [t for t in yaml_tr if t not in prose_tr]
        extra = [t for t in prose_tr if t not in yaml_tr]
        fail(f"transitions: prose and contract differ; missing in prose {missing}; extra in prose {extra}")

    rows = prose_table(text, "### Outcomes")
    prose_out = {(words(r[0])[0], r[1]): words(r[2]) for r in rows if words(r[0])}
    yaml_out = {}
    for act, spec in contract["outcomes"].items():
        if isinstance(spec, dict):
            for subject, outs in spec.items():
                yaml_out[(act, subject)] = outs
        else:
            yaml_out[(act, contract["verbs"][act]["outcome_subject"])] = spec
    if prose_out != yaml_out:
        fail(f"outcomes: prose {prose_out} != contract {yaml_out}")

    rows = prose_table(text, "### Roles and their verbs")
    prose_roles = {words(r[0])[0]: words(r[1]) for r in rows if words(r[0])}
    yaml_roles = {k: v["verbs"] for k, v in contract["roles"].items()}
    if prose_roles != yaml_roles:
        fail(f"roles: prose {prose_roles} != contract {yaml_roles}")
    for role, held in yaml_roles.items():
        for v in held:
            if v not in verbs or verbs[v]["kind"] != "act":
                fail(f"role {role}: holds {v}, which is not a performed verb")
    for v, spec in verbs.items():
        holders = sorted(r for r, held in yaml_roles.items() if v in held)
        if holders != sorted(spec["roles"]):
            fail(f"verb {v}: lists roles {spec['roles']}, but the roles holding it are {holders}")

    rows = prose_table(text, "### Levels")
    prose_levels = [words(r[0])[0] for r in rows if words(r[0])]
    if prose_levels != contract["levels"]["initial"]:
        fail(f"levels: prose {prose_levels} != {contract['levels']['initial']}")

    rows = prose_table(text, "### Reference kinds")
    prose_kinds = [words(r[0])[0] for r in rows if words(r[0])]
    if prose_kinds != list(contract["references"]["kinds"]):
        fail(f"reference kinds: prose {prose_kinds} != {list(contract['references']['kinds'])}")

    rows = prose_table(text, "### Field limits")
    prose_limits = {}
    prose_fields = {}
    for r in rows:
        nums = re.findall(r"\d[\d,]*", r[1])
        if words(r[0]) and nums:
            prose_limits[words(r[0])[0]] = int(nums[0].replace(",", ""))
            prose_fields[words(r[0])[0]] = words(r[2])
    if prose_limits != contract["limits"]:
        fail(f"limits: prose {prose_limits} != {contract['limits']}")
    if prose_fields != contract["limit_fields"]:
        fail(f"limit fields: prose {prose_fields} != {contract['limit_fields']}")
    if "aim for one line" not in text.lower():
        fail("limits: prose must keep the title guidance 'aim for one line'")

    rows = prose_table(text, "### The fixed queries")
    prose_queries = [words(r[0])[0] for r in rows if words(r[0])]
    if prose_queries != list(contract["queries"]):
        fail(f"queries: prose {prose_queries} != {list(contract['queries'])}")

    # Rule 5: the five no-recursion rules, lettered a to e, with the worked
    # example they cite.
    m = re.search(r"^### No recursive invalidation$(.*?)^##", text, re.S | re.M)
    if not m:
        fail("prose: section 'No recursive invalidation' not found")
    else:
        letters = re.findall(r"^\s*([a-e])\. \*\*", m.group(1), re.M)
        if letters != list("abcde"):
            fail(f"no recursive invalidation: prose rules {letters} != a to e")
        if NO_LOOP_EXAMPLE not in m.group(1):
            fail(f"no recursive invalidation: prose does not cite {NO_LOOP_EXAMPLE}")
    if list(contract["no_recursive_invalidation"]) != list("abcde"):
        fail("no recursive invalidation: contract rules are not a to e")

    # Closed questions: none may remain open.
    if re.search(r"^## \d+\. Open questions", text, re.M):
        fail("prose: an 'Open questions' section remains; review 1 closed them")

    for w in REMOVED_STATE_WORDS:
        if f"`{w}`" in text:
            fail(f"prose: removed state word `{w}` appears")
    for w in REMOVED_PHASE_WORDS:
        if re.search(rf"\b{w}\b", text):
            fail(f"prose: removed two-phase word {w!r} appears")

    window = contract["parameters"]["edit_window_seconds"]
    if window != 600 or "10 minutes" not in text:
        fail(f"edit window: contract {window}s; prose must say 10 minutes")

    version = (ROOT.parent / "VERSION").read_text().strip()
    if contract["bedrock"] != version:
        fail(f"version: contract {contract['bedrock']} != VERSION {version}")
    if f"Version {version}" not in text:
        fail(f"version: prose does not state 'Version {version}'")


# --------------------------------------------------------------------------
# The contract's own rules
# --------------------------------------------------------------------------


def state_sets(contract: dict) -> dict[str, list[str]]:
    out = {n: s["states"] for n, s in contract["nouns"].items()}
    out["Plan"] = contract["group"]["Plan"]["states"]
    return out


def made_by(contract: dict, noun: str) -> str:
    if noun == "Plan":
        return contract["group"]["Plan"]["made_by"]
    return contract["nouns"][noun]["made_by"]


def first_state(contract: dict, noun: str) -> str:
    """The past tense of the verb that makes the noun, or the exception's first word."""
    rule = contract["state_rule"]
    if noun in rule["exception"]:
        return rule["exception"][noun][0]
    return rule["past_tense"][made_by(contract, noun)]


def check_contract(contract: dict) -> None:
    """Review 1, rule 2: a state is the past tense of the last verb applied;
    the one exception is the Promise; every noun may also be superseded or
    revoked (a Witness only revoked). No removed word returns."""
    rule = contract["state_rule"]
    past = rule["past_tense"]
    exception = rule["exception"]
    sets = state_sets(contract)
    acts = [v for v, s in contract["verbs"].items() if s["kind"] in ("act", "transition")]
    acts += list(contract["structural_acts"])
    if sorted(past) != sorted(set(acts) - set(rule["no_state"])):
        fail(f"state rule: past_tense covers {sorted(past)}, not every state-giving act")

    for noun, states in sets.items():
        first = first_state(contract, noun)
        if noun in exception:
            allowed = set(exception[noun]) | set(WITHDRAWN)
        else:
            allowed = set(past.values())
        if states[0] != first:
            fail(f"state rule: {noun}'s first state {states[0]} != {first}")
        for s in states:
            if s not in allowed:
                fail(f"state rule: {noun} state {s} is not the past tense of a verb")
            if s in REMOVED_STATE_WORDS:
                fail(f"state rule: {noun} uses removed state word {s}")
        withdrawn = [s for s in states if s in WITHDRAWN]
        want = ["revoked"] if noun in rule["never_superseded"] + ["Plan"] else list(WITHDRAWN)
        if withdrawn != want:
            fail(f"state rule: {noun} withdrawn states {withdrawn} != {want}")
        from_tr = []
        for t in contract["transitions"]:
            if t["noun"] == noun and t["to"] not in from_tr:
                from_tr.append(t["to"])
        if from_tr != states:
            fail(f"state rule: {noun} states {states} != states reached by transitions {from_tr}")

    for t in contract["transitions"]:
        noun, to = t["noun"], t["to"]
        if t.get("recompute"):
            if not set(t["by"]) <= set(WITHDRAWN_BY) or to in WITHDRAWN:
                fail(f"transition {t}: a recomputation follows only revoke or supersede")
            continue
        if noun in exception and to in exception[noun]:
            continue
        for v in t["by"]:
            want = first_state(contract, noun) if not t["from"] else past.get(v)
            if to != want:
                fail(f"state rule: {noun} {t['from']} -> {to} by {v}; the state must be {want}")

    for act, spec in contract["outcomes"].items():
        values = sum(spec.values(), []) if isinstance(spec, dict) else spec
        for v in values:
            if v in REMOVED_STATE_WORDS or v in set(past.values()):
                fail(f"outcomes: {act} outcome {v} is a state word")

    raw = CONTRACT.read_text()
    for w in REMOVED_PHASE_WORDS:
        if re.search(rf"\b{w}\b", raw):
            fail(f"contract: removed two-phase word {w!r} appears")

    reach = contract["one_step"]
    all_acts = [v for v, s in contract["verbs"].items() if s["kind"] == "act"]
    all_acts += list(contract["structural_acts"])
    if sorted(reach) != sorted(all_acts):
        fail(f"one_step: covers {sorted(reach)}, not every act {sorted(all_acts)}")
    for v, tokens in reach.items():
        for tok in tokens:
            if tok not in REACH_TOKENS:
                fail(f"one_step: {v} names unknown reach {tok}")
    if contract["recomputation"]["generates_acts"] is not False:
        fail("recomputation: must never generate acts")


WITHDRAWN_BY = ("revoke", "supersede")


# --------------------------------------------------------------------------
# Schema against contract
# --------------------------------------------------------------------------


def schema_refs(node, path=()):
    """Yield (path, property name, property schema) for every object property."""
    if isinstance(node, dict):
        for name, sub in node.get("properties", {}).items():
            yield path, name, sub
        for k, v in node.items():
            yield from schema_refs(v, path + (k,))
    elif isinstance(node, list):
        for i, v in enumerate(node):
            yield from schema_refs(v, path + (i,))


def check_schema(schema: dict, contract: dict) -> None:
    jsonschema.Draft202012Validator.check_schema(schema)
    defs = schema["$defs"]
    verbs = [v for v, s in contract["verbs"].items() if s["kind"] == "act"]
    act_names = verbs + list(contract["structural_acts"])
    if defs["verb"]["enum"] != act_names:
        fail(f"schema verb enum {defs['verb']['enum']} != contract acts {act_names}")
    for name, states in state_sets(contract).items():
        enum = defs["state"]["properties"].get(name, {}).get("enum")
        if enum != states:
            fail(f"schema states for {name} {enum} != {states}")
    for field, limit in contract["limits"].items():
        got = defs.get(field, {}).get("maxLength")
        if got != limit:
            fail(f"schema limit {field} {got} != contract {limit}")
    # Every field the review names is held to its limit.
    for kind, names in contract["limit_fields"].items():
        for path, name, sub in schema_refs(defs):
            if name in names and path[:1] != ("verb",):
                if kind == "result" and path[:1] != ("witness",):
                    continue
                if sub.get("$ref") != f"#/$defs/{kind}":
                    fail(f"schema: field {name} at {'/'.join(map(str, path))} is not limited as {kind}")
    if defs["level"]["examples"] != contract["levels"]["initial"]:
        fail("schema level examples != contract initial levels")
    if defs["reference"]["properties"]["kind"]["enum"] != list(contract["references"]["kinds"]):
        fail("schema reference kinds != contract reference kinds")
    if schema["properties"]["protocol"]["const"] != contract["bedrock"]:
        fail("schema protocol const != contract version")
    for verb in act_names:
        if f"payload_{verb}" not in defs:
            fail(f"schema has no payload definition for {verb}")
    for noun, spec in contract["nouns"].items():
        if spec["prefix"] and not re.match(defs[f"id_{noun}"]["pattern"], f"{spec['prefix']}-1"):
            fail(f"schema id pattern for {noun} does not admit {spec['prefix']}-1")
    # A Plan holds only its member nouns: every field naming a Plan member
    # admits exactly those ids.
    member = {"anyOf": [{"$ref": f"#/$defs/id_{n}"} for n in contract["group"]["Plan"]["members"]]}
    if defs.get("id_plan_member", {}).get("anyOf") != member["anyOf"]:
        fail(f"schema id_plan_member {defs.get('id_plan_member')} != {member}")
    regroup = defs["payload_regroup"]["properties"]
    waits = defs["waits"]["items"]["properties"]
    for where, sub in (
        ("plan.members", defs["plan"]["properties"]["members"]["items"]),
        ("payload_regroup.add_members", regroup["add_members"]["items"]),
        ("payload_regroup.remove_members", regroup["remove_members"]["items"]),
        ("waits.member", waits["member"]),
        ("waits.upon", waits["upon"]),
    ):
        if sub != {"$ref": "#/$defs/id_plan_member"}:
            fail(f"schema {where} admits {sub}, not only Plan members")
    out = contract["outcomes"]
    if defs["payload_judge"]["properties"]["verdict"]["enum"] != out["judge"]:
        fail("schema judge verdicts != contract judge outcomes")
    if defs["payload_evaluate"]["properties"]["outcome"]["enum"] != out["evaluate"]:
        fail("schema evaluate outcomes != contract evaluate outcomes")
    decide = defs["payload_decide"]["properties"]["outcomes"]["items"]["properties"]["outcome"]["enum"]
    if decide != sum(out["decide"].values(), []):
        fail("schema decide outcomes != contract decide outcomes")
    raw = SCHEMA.read_text()
    for w in REMOVED_PHASE_WORDS:
        if re.search(rf"\b{w}\b", raw):
            fail(f"schema: removed two-phase word {w!r} appears")
    for w in REMOVED_STATE_WORDS:
        if f'"{w}"' in raw:
            fail(f"schema: removed state word {w!r} appears")


# --------------------------------------------------------------------------
# Reference projector
# --------------------------------------------------------------------------


class Refused(Exception):
    def __init__(self, code: str, msg: str):
        super().__init__(msg)
        self.code = code


def noun_of(record_id: str, contract: dict) -> str:
    for name, spec in contract["nouns"].items():
        if record_id.startswith(spec["prefix"] + "-"):
            return name
    if record_id.startswith(contract["group"]["Plan"]["prefix"] + "-"):
        return "Plan"
    raise Refused("unknown_id", f"unknown record id {record_id}")


MADE_KEYS = ("invariant", "gap", "candidate", "decision", "promise", "oracle", "witness", "reference", "plan")


class Projector:
    """Replays acts. After every act it rebuilds every record's state from the
    acts that still stand, so it never moves a state by hand."""

    def __init__(self, contract: dict):
        self.c = contract
        self.past = contract["state_rule"]["past_tense"]
        self.state: dict[str, str] = {}
        self.record: dict[str, dict] = {}
        self.hist: dict[str, list[dict]] = {}  # record -> state-giving acts, in order
        self.author: dict[str, tuple[str, datetime]] = {}  # record -> (agent, created)
        self.subjects: dict[str, list[str]] = {}  # Decision -> its outcome subjects
        self.judged: set[tuple[str, str]] = set()  # (Witness, Oracle)
        self.log: list[dict] = []
        self.applied: set[tuple] = set()
        self.allowed = {
            (t["noun"], f, t["to"], v)
            for t in contract["transitions"]
            for v in t["by"]
            for f in (t["from"] or [None])
        }

    # -- the state rule ----------------------------------------------------

    def withdrawn(self, rid: str) -> bool:
        return any(e["verb"] in WITHDRAWN_BY for e in self.hist.get(rid, []))

    def stands(self, e: dict) -> bool:
        return e.get("rests_on") is None or not self.withdrawn(e["rests_on"])

    def derive(self, rid: str) -> str:
        h = self.hist[rid]
        for e in h:
            if e["verb"] in WITHDRAWN_BY:
                return e["state"]  # revoke and supersede always stand
        if noun_of(rid, self.c) == "Promise":
            verdicts = [
                e for e in h
                if e["verb"] == "judge" and self.stands(e) and e["verdict"] != "inconclusive"
            ]
            return "assured" if verdicts and verdicts[-1]["verdict"] == "holds" else "asserted"
        return [e for e in h if self.stands(e)][-1]["state"]

    def give(self, rid: str, act: dict, state: str, **extra) -> None:
        if self.withdrawn(rid) and act["verb"] not in WITHDRAWN_BY:
            raise Refused("transition_not_allowed", f"{rid} is withdrawn; {act['verb']} does not apply")
        self.hist.setdefault(rid, []).append({"act": act["id"], "verb": act["verb"], "state": state, **extra})

    def rebuild(self, verb: str) -> None:
        for rid in self.hist:
            new, old = self.derive(rid), self.state.get(rid)
            if new == old:
                continue
            noun = noun_of(rid, self.c)
            by = "assure" if noun == "Promise" and new == "assured" and verb == "judge" else verb
            key = (noun, old, new, by)
            if key not in self.allowed:
                raise Refused("transition_not_allowed", f"{noun} {rid}: {old} -> {new} by {by}")
            self.applied.add(key)
            self.state[rid] = new

    # -- acts ----------------------------------------------------------------

    def create(self, rec: dict, noun: str, act: dict) -> None:
        rid = rec["id"]
        if noun_of(rid, self.c) != noun:
            raise Refused("wrong_noun", f"{rid} is not a {noun}")
        if rid in self.hist:
            raise Refused("duplicate_id", f"{rid} exists")
        self.record[rid] = copy.deepcopy(rec)
        self.author[rid] = (act["actor"]["agent"], when(act))
        self.give(rid, act, first_state(self.c, noun))

    def need(self, rid: str, noun: str) -> dict:
        if rid not in self.record or noun_of(rid, self.c) != noun:
            raise Refused("missing_input", f"{rid} is not a recorded {noun}")
        return self.record[rid]

    def latest_outcome(self, rid: str) -> str | None:
        decided = [e for e in self.hist[rid] if e["verb"] == "decide" and self.stands(e)]
        return decided[-1]["outcome"] if decided else None

    def add_member(self, members: list[str], m: str) -> None:
        noun = noun_of(m, self.c)
        if noun not in self.c["group"]["Plan"]["members"]:
            raise Refused("bad_member", f"{m} cannot be a Plan member")
        self.need(m, noun)
        if m in members:
            raise Refused("bad_member", f"{m} is already a member")
        members.append(m)

    def check_wait(self, members: list[str], w: dict) -> None:
        if w["member"] not in members or w["upon"] not in members:
            raise Refused("bad_member", f"waits_on {w} names a non-member")

    def making_act(self, act: dict) -> dict:
        """The act that made the record an act's edit window belongs to: the
        act itself when it made a record, the end of its amend chain when it
        is an amendment. Refused when that act made no record."""
        target = act
        while target["verb"] == "amend":
            tid = target["payload"]["target_act"]
            found = next((a for a in self.log if a["id"] == tid), None)
            if found is None:
                raise Refused("missing_input", f"{tid} is not a recorded act")
            target = found
        if not any(isinstance(target["payload"].get(k), dict) for k in MADE_KEYS):
            raise Refused("not_amendable", f"{target['id']} ({target['verb']}) made no record to amend")
        return target

    def apply(self, act: dict) -> None:
        saved = copy.deepcopy(
            (self.state, self.record, self.hist, self.author, self.subjects, self.judged, self.applied)
        )
        try:
            self.log.append(act)
            self._apply(act)
            self.rebuild(act["verb"])
        except Refused:
            self.log.pop()
            (self.state, self.record, self.hist, self.author, self.subjects, self.judged, self.applied) = saved
            raise

    def _apply(self, act: dict) -> None:
        v, p = act["verb"], act["payload"]
        if v == "stipulate":
            for b in p.get("basis", []):
                self.need(b, noun_of(b, self.c))
            self.create(p["invariant"], "Invariant", act)
        elif v == "declare":
            if "arose_in" in p and not any(a["id"] == p["arose_in"] for a in self.log):
                raise Refused("missing_input", f"arose_in {p['arose_in']} is not a recorded act")
            self.create(p["gap"], "Gap", act)
        elif v == "formulate":
            for r in p["responds_to"]:
                self.need(r, noun_of(r, self.c))
            self.create(p["candidate"], "Candidate", act)
        elif v == "evaluate":
            cid = p["candidate"]
            self.need(cid, "Candidate")
            for r in p.get("findings", []):
                self.need(r, "Reference")
            self.give(cid, act, self.past[v], outcome=p["outcome"])
        elif v == "decide":
            for r in p.get("considered", []):
                self.need(r, noun_of(r, self.c))
            did = p["decision"]["id"]
            self.create(p["decision"], "Decision", act)
            self.subjects[did] = []
            for o in p.get("outcomes", []):
                subj, out = o["subject"], o["outcome"]
                noun = noun_of(subj, self.c)
                self.need(subj, noun)
                if out not in self.c["outcomes"]["decide"].get(noun, []):
                    raise Refused("bad_outcome", f"{out} is not an outcome for a {noun}")
                self.give(subj, act, self.past[v], outcome=out, rests_on=did)
                self.subjects[did].append(subj)
        elif v == "mint":
            basis = p["basis"]
            if "decision" in basis:
                self.need(basis["decision"], "Decision")
            else:
                self.need(basis["instruction"], "Reference")
            if "from_candidate" in p:
                if "decision" not in basis:
                    raise Refused("missing_input", "a Promise minted from a Candidate cites the Decision")
                self.need(p["from_candidate"], "Candidate")
                if self.latest_outcome(p["from_candidate"]) != "accept":
                    raise Refused("missing_input", "the Candidate was not accepted")
                accepted_by = [
                    e["rests_on"] for e in self.hist[p["from_candidate"]]
                    if e["verb"] == "decide" and e["outcome"] == "accept" and self.stands(e)
                ]
                if basis["decision"] not in accepted_by:
                    raise Refused("wrong_basis", f"{basis['decision']} did not accept {p['from_candidate']}")
            for g in p.get("addresses", []):
                self.need(g, "Gap")
            self.create(p["promise"], "Promise", act)
        elif v == "define":
            o = p["oracle"]
            self.need(o["judges"], "Promise")
            self.create(o, "Oracle", act)
        elif v == "produce":
            w = p["witness"]
            self.need(w["observes"], "Promise")
            for e in w["evidence"]:
                self.need(e, "Reference")
            self.create(w, "Witness", act)
        elif v == "refine":
            t = p["target"]
            noun = noun_of(t, self.c)
            self.need(t, noun)
            if noun == "Witness":
                w = p.get("witness")
                if not w or w["observes"] != self.record[t]["observes"]:
                    raise Refused("missing_input", "refining a Witness produces a new Witness of the same Promise")
                if self.withdrawn(t):
                    raise Refused("witness_revoked", f"{t} is revoked; produce a new Witness instead")
                for e in w["evidence"]:
                    self.need(e, "Reference")
                self.create(w, "Witness", act)
            elif noun in ("Gap", "Candidate"):
                if "sighting" not in p:
                    raise Refused("missing_input", "refining a Gap or Candidate adds a sighting")
                for e in p["sighting"].get("evidence", []):
                    self.need(e, "Reference")
            else:
                raise Refused("not_refinable", f"a {noun} is not refined")
        elif v == "judge":
            pid, oid, wid = p["promise"], p["oracle"], p["witness"]
            self.need(pid, "Promise")
            o = self.need(oid, "Oracle")
            w = self.need(wid, "Witness")
            if o["judges"] != pid or w["observes"] != pid:
                raise Refused("mismatched_inputs", "the Oracle and Witness must concern the judged Promise")
            if self.withdrawn(oid):
                raise Refused("oracle_not_in_force", f"{oid} is {self.state[oid]}")
            if self.withdrawn(wid):
                raise Refused("witness_revoked", f"{wid} is revoked")
            if (wid, oid) in self.judged:
                raise Refused("already_judged", f"{wid} is already judged against {oid}; a rejudge needs a new Witness or a new Oracle")
            if p["verdict"] == "does_not_hold" and not p.get("failure_evidence"):
                raise Refused("missing_input", "does_not_hold cites the demonstrated in-scope failure")
            self.judged.add((wid, oid))
            self.give(wid, act, self.past[v])
            self.give(pid, act, self.past[v], verdict=p["verdict"], rests_on=wid)
        elif v in WITHDRAWN_BY:
            t = p["target"]
            noun = noun_of(t, self.c)
            self.need(t, noun)
            if self.withdrawn(t):
                raise Refused("transition_not_allowed", f"{t} is already {self.state[t]}")
            if v == "supersede":
                s = p["successor"]
                if noun_of(s, self.c) != noun:
                    raise Refused("wrong_noun", "a successor is the same noun")
                self.need(s, noun)
                if self.withdrawn(s):
                    raise Refused("successor_not_current", f"{s} is {self.state[s]}")
            self.give(t, act, self.past[v])
        elif v == "store":
            self.create(p["reference"], "Reference", act)
        elif v == "group":
            plan = p["plan"]
            members: list[str] = []
            for m in plan["members"]:
                self.add_member(members, m)
            for w in plan.get("waits_on", []):
                self.check_wait(members, w)
            self.create(plan, "Plan", act)
        elif v == "regroup":
            plan = self.need(p["plan"], "Plan")
            members = plan["members"]
            waits = plan.setdefault("waits_on", [])
            # Removals first, then additions, so a member leaves with its
            # links and arrives with them in one act.
            for w in p.get("remove_waits", []):
                if w not in waits:
                    raise Refused("bad_member", f"{p['plan']} has no waits_on link {w}")
                waits.remove(w)
            for m in p.get("remove_members", []):
                if m not in members:
                    raise Refused("bad_member", f"{m} is not a member of {p['plan']}")
                if any(m in (w["member"], w["upon"]) for w in waits):
                    raise Refused("bad_member", f"{m} is still named by a waits_on link of {p['plan']}")
                members.remove(m)
            for m in p.get("add_members", []):
                self.add_member(members, m)
            for w in p.get("add_waits", []):
                self.check_wait(members, w)
                if w in waits:
                    raise Refused("bad_member", f"{p['plan']} already has waits_on link {w}")
                waits.append(w)
            self.give(p["plan"], act, self.past[v])
        elif v == "relate":
            for r in (p["from"], p["to"]):
                if not r.startswith("scope:"):
                    self.need(r, noun_of(r, self.c))
        elif v == "amend":
            # The window runs from the act that made the record; an amendment
            # of an amendment corrects the same record and never extends it.
            target = self.making_act(act)
            if target["actor"]["agent"] != act["actor"]["agent"]:
                raise Refused("not_author", "only the author amends within the edit window")
            window = self.c["parameters"]["edit_window_seconds"]
            if (when(act) - when(target)).total_seconds() > window:
                raise Refused("edit_window_closed", "the edit window has closed; supersede or revoke")
        else:
            raise Refused("unknown_verb", v)


# The records an act may change, by the tokens of the contract's one_step map.
REACH_TOKENS = {
    "made": lambda proj, p: {p[k]["id"] for k in MADE_KEYS if isinstance(p.get(k), dict)},
    "candidate": lambda proj, p: {p["candidate"]} if isinstance(p.get("candidate"), str) else set(),
    "subjects": lambda proj, p: {o["subject"] for o in p.get("outcomes", [])},
    "witness": lambda proj, p: {p["witness"]} if isinstance(p.get("witness"), str) else set(),
    "promise": lambda proj, p: {p["promise"]} if isinstance(p.get("promise"), str) else set(),
    "plan": lambda proj, p: {p["plan"]} if isinstance(p.get("plan"), str) else set(),
    "target": lambda proj, p: {p["target"]} if "target" in p else set(),
    "promise_of_witness": lambda proj, p: (
        {proj.record[p["target"]]["observes"]} if p.get("target", "").startswith("W-") else set()
    ),
    "subjects_of_decision": lambda proj, p: set(proj.subjects.get(p.get("target", ""), [])),
}


def reach(contract: dict, proj: Projector, act: dict) -> set[str]:
    out: set[str] = set()
    for tok in contract["one_step"][act["verb"]]:
        out |= REACH_TOKENS[tok](proj, act["payload"])
    return out


def when(act: dict) -> datetime:
    return datetime.fromisoformat(act["recorded_at"].replace("Z", "+00:00"))


def merge(base: dict, over: dict) -> dict:
    out = copy.deepcopy(base)
    for k, v in over.items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = merge(out[k], v)
        else:
            out[k] = copy.deepcopy(v)
    return out


def check_examples(schema: dict, contract: dict) -> tuple[set[tuple], set[str]]:
    validator = jsonschema.Draft202012Validator(
        schema, format_checker=jsonschema.Draft202012Validator.FORMAT_CHECKER
    )
    exercised: set[tuple] = set()
    refusals: set[str] = set()
    files = sorted(EXAMPLES.glob("*.yaml"))
    if not files:
        fail("examples: none found")
    for path in files:
        raw = path.read_text()
        for w in REMOVED_PHASE_WORDS:
            if re.search(rf"\b{w}\b", raw):
                fail(f"{path.name}: removed two-phase word {w!r} appears")
        ex = yaml.safe_load(raw)
        name = path.name
        proj = Projector(contract)
        refused = None
        crashed = False
        trace: dict[str, list[str]] = {}
        for i, raw_act in enumerate(ex["acts"]):
            act = merge(ex.get("defaults", {}), raw_act)
            invalid = list(validator.iter_errors(act))
            for err in invalid:
                fail(f"{name} act {i} ({act.get('id')}): schema: {err.message} at {list(err.absolute_path)}")
            if invalid:
                break
            before = dict(proj.state)
            try:
                proj.apply(act)
            except Refused as r:
                refused = (i, r)
                break
            except Exception as e:  # a defect in the example or the projector
                fail(f"{name} act {i} ({act.get('id')}): projector raised {type(e).__name__}: {e}")
                crashed = True
                break
            if "edit_window_closes_at" in act:
                try:
                    made = proj.making_act(act)
                except Refused as r:
                    fail(f"{name} act {i} ({act['id']}): carries edit_window_closes_at but {r}")
                    continue
                closes = when(made) + timedelta(seconds=contract["parameters"]["edit_window_seconds"])
                if when({"recorded_at": act["edit_window_closes_at"]}) != closes:
                    fail(f"{name} act {i} ({act['id']}): edit_window_closes_at {act['edit_window_closes_at']}"
                         f" != {made['id']} recorded_at + window ({closes.isoformat()})")
            # Rule 5a: recomputation never creates work.
            if len(proj.log) != i + 1:
                fail(f"{name} act {i}: the log holds {len(proj.log)} acts after {i + 1} were submitted")
            # Rule 5d: one step, never a cascade.
            changed = {r for r, s in proj.state.items() if before.get(r) != s}
            outside = changed - reach(contract, proj, act)
            if outside:
                fail(f"{name} act {i} ({act['id']} {act['verb']}): changed {sorted(outside)} outside its one-step reach")
            for r in changed:
                trace.setdefault(r, []).append(proj.state[r])
        if crashed:
            continue
        expect = ex["expect"]
        if "refused" in expect:
            want = expect["refused"]
            refusals.add(want["code"])
            if want["code"] not in contract["refusals"]:
                fail(f"{name}: refusal {want['code']} is not listed in the contract's refusals")
            if refused is None:
                fail(f"{name}: expected refusal {want} but every act applied")
            elif refused[1].code != want["code"] or refused[0] != want["act_index"]:
                fail(f"{name}: expected refusal {want}, got act {refused[0]} {refused[1].code}: {refused[1]}")
        elif refused is not None:
            fail(f"{name}: act {refused[0]} refused: {refused[1].code}: {refused[1]}")
        for rid, st in expect.get("states", {}).items():
            if proj.state.get(rid) != st:
                fail(f"{name}: {rid} expected {st}, projected {proj.state.get(rid)}")
            if st in REMOVED_STATE_WORDS:
                fail(f"{name}: {rid} expects removed state word {st}")
        for pid, want_plan in expect.get("plans", {}).items():
            got = proj.record.get(pid, {})
            got_plan = {"members": got.get("members"), "waits_on": got.get("waits_on", [])}
            if got_plan != want_plan:
                fail(f"{name}: {pid} holds {got_plan}, expected {want_plan}")
        for rid, want_trace in expect.get("trace", {}).items():
            if trace.get(rid) != want_trace:
                fail(f"{name}: {rid} passed through {trace.get(rid)}, expected {want_trace}")
        if f"contract/examples/{name}" == NO_LOOP_EXAMPLE:
            check_no_loop_example(name, ex, trace, refused)
        exercised |= proj.applied
    if not (ROOT.parent / NO_LOOP_EXAMPLE).exists():
        fail(f"examples: {NO_LOOP_EXAMPLE} (rule 5 worked example) is missing")
    return exercised, refusals


def check_no_loop_example(name: str, ex: dict, trace: dict, refused) -> None:
    """Rule 5 worked example: assured, a later does_not_hold, a fix, a new
    Witness, holds again; the Oracle superseded without losing assurance; a
    refined Witness judged like any other; and a rejudge of a judged pair
    refused, so the loop never starts."""
    acts = ex["acts"]
    verbs = [a["verb"] for a in acts]
    promises = [r for r in trace if r.startswith("P-")]
    if len(promises) != 1 or trace[promises[0]] != ["asserted", "assured", "asserted", "assured"]:
        fail(f"{name}: the Promise must pass asserted, assured, asserted, assured; got {trace}")
    if "refine" not in verbs:
        fail(f"{name}: rule 5e needs a Witness made by refine")
    if not any(a["verb"] == "supersede" and a["payload"]["target"].startswith("O-") for a in acts):
        fail(f"{name}: rule 5c needs a superseded Oracle")
    if refused is None or refused[1].code != "already_judged" or refused[0] != len(acts) - 1:
        fail(f"{name}: rule 5b needs the last act to be a refused rejudge of a judged pair")


def check_manifest() -> None:
    import hashlib

    manifest = json.loads((ROOT.parent / "manifest.json").read_text())
    listed = {e["path"]: e["sha256"] for e in manifest.get("contract", [])}
    for p in (PROSE, CONTRACT, SCHEMA):
        rel = str(p.relative_to(ROOT.parent))
        digest = hashlib.sha256(p.read_bytes()).hexdigest()
        if listed.get(rel) != digest:
            fail(f"manifest: {rel} digest {listed.get(rel)} != file {digest}")
    version = (ROOT.parent / "VERSION").read_text().strip()
    if manifest.get("version") != version:
        fail(f"manifest: version {manifest.get('version')} != VERSION {version}")


def main() -> int:
    for p in (PROSE, CONTRACT, SCHEMA):
        if not p.exists():
            fail(f"missing {p.relative_to(ROOT.parent)}")
    if errors:
        return report()
    text = PROSE.read_text()
    contract = yaml.safe_load(CONTRACT.read_text())
    schema = json.loads(SCHEMA.read_text())
    broken = False
    for step in (
        lambda: check_contract(contract),
        lambda: check_prose(text, contract),
        lambda: check_schema(schema, contract),
        check_manifest,
    ):
        try:
            step()
        except (KeyError, TypeError, AttributeError, IndexError) as e:
            fail(f"structure: {type(e).__name__} {e}")
            broken = True
    if broken:
        return report()
    exercised, refusals = check_examples(schema, contract)
    for t in contract["transitions"]:
        for v in t["by"]:
            keys = {(t["noun"], f, t["to"], v) for f in (t["from"] or [None])}
            if not keys & exercised:
                fail(f"transition {t['noun']} {t['from']} -> {t['to']} by {v} is exercised by no example")
    for code in contract["refusals"]:
        if code not in refusals:
            fail(f"refusal {code} is exercised by no example")
    return report()


def report() -> int:
    if errors:
        for e in errors:
            print("FAIL", e)
        print(f"{len(errors)} disagreement(s)")
        return 1
    print("OK: prose, contract, schema and examples agree")
    return 0


if __name__ == "__main__":
    sys.exit(main())
